dist: trusty
sudo: required 
language: cpp
os:
- linux
branches:
  only:
  - master

env:
  matrix:
  - LIBVARIANT_USE_STD_STRING=ON
  - LIBVARIANT_USE_STD_STRING=OFF

install:
- cd $TRAVIS_BUILD_DIR/ci/travis; ./install_googletest.sh;

script:
- cd $TRAVIS_BUILD_DIR/ci/travis; ./build_library.sh;

after_success:
- cd $TRAVIS_BUILD_DIR/ci/travis; ./test_script.sh;

notifications:
  email: true
